[pytest]
asyncio_mode = auto
asyncio_default_test_loop_scope = function
testpaths = tests
filterwarnings =
    ignore::RuntimeWarning:backports.asyncio.runner.runner
    ignore::RuntimeWarning:pytest_asyncio.plugin