from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path
from typing import Any, Dict, List, Optional

# OpenMontage VideoStitch (after: pip install -e /path/to/OpenMontage)
from tools.video.video_stitch import VideoStitch, ToolResult


def collect_clips_from_render_commands(base_dir: Path) -> List[str]:
    """Extract clip paths from the render-commands.json generated by the pipeline."""
    commands_path = base_dir / "exports" / "render-commands.json"
    if not commands_path.exists():
        # Fallback: scan renders directory
        renders_dir = base_dir / "renders"
        if renders_dir.exists():
            return sorted(str(p) for p in renders_dir.glob("*.mp4"))
        return []

    commands = json.loads(commands_path.read_text(encoding="utf-8"))
    clips: List[str] = []

    # Primary: scenes array with ids
    for scene in commands.get("scenes", []):
        scene_id = scene.get("id")
        if scene_id is not None:
            clip_path = base_dir / "renders" / f"scene_{scene_id:02d}.mp4"
            if clip_path.exists():
                clips.append(str(clip_path))

    # Fallback: direct clip_paths if present
    if not clips and "clip_paths" in commands:
        for p in commands["clip_paths"]:
            path = Path(p)
            if not path.is_absolute():
                path = base_dir / path
            if path.exists():
                clips.append(str(path))

    # Final fallback: glob renders dir
    if not clips:
        renders_dir = base_dir / "renders"
        if renders_dir.exists():
            clips = sorted(str(p) for p in renders_dir.glob("*.mp4"))

    return clips


def finalize(
    base_dir: Path,
    output_path: Path,
    transition: str = "cut",               # cut | crossfade | fade
    transition_duration: float = 0.5,
    auto_normalize: bool = True,
    codec: str = "libx264",
    crf: int = 23,
    preset: str = "medium",
    dry_run: bool = False,
) -> Dict[str, Any]:
    """Run final stitching using OpenMontage VideoStitch."""
    clips = collect_clips_from_render_commands(base_dir)

    if not clips:
        return {
            "output": str(output_path),
            "success": False,
            "error": "No clips found in renders/",
            "method": "openmontage_video_stitch",
        }

    if len(clips) == 1:
        # Single clip: just copy
        output_path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(clips[0], output_path)
        return {
            "output": str(output_path),
            "success": True,
            "method": "copy",
            "clip_count": 1,
        }

    # Ensure output directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)

    stitcher = VideoStitch()

    inputs = {
        "operation": "stitch",
        "clips": clips,
        "output_path": str(output_path),
        "transition": transition,
        "transition_duration": transition_duration,
        "auto_normalize": auto_normalize,
        "codec": codec,
        "crf": crf,
        "preset": preset,
        "dry_run": dry_run,
    }

    result: ToolResult = stitcher.execute(inputs)

    if result.success:
        data = result.data or {}
        return {
            "output": str(output_path),
            "success": True,
            "method": "openmontage_video_stitch",
            "clip_count": len(clips),
            "transition": transition,
            "transition_duration": transition_duration if transition != "cut" else 0,
            "auto_normalized": data.get("auto_normalized"),
            "duration": data.get("duration"),
            "file_size_bytes": data.get("file_size_bytes"),
            "artifacts": result.artifacts,
        }
    else:
        return {
            "output": str(output_path),
            "success": False,
            "error": result.error,
            "method": "openmontage_video_stitch",
        }


def main() -> None:
    parser = argparse.ArgumentParser(description="Run final stitching via OpenMontage VideoStitch.")
    parser.add_argument("base_dir", help="Project base directory (contains renders/, exports/)")
    parser.add_argument("output_path", help="Output video file path")
    parser.add_argument("--transition", choices=["cut", "crossfade", "fade"], default="cut")
    parser.add_argument("--transition-duration", type=float, default=0.5)
    parser.add_argument("--no-normalize", dest="auto_normalize", action="store_false")
    parser.add_argument("--codec", default="libx264")
    parser.add_argument("--crf", type=int, default=23)
    parser.add_argument("--preset", default="medium")
    parser.add_argument("--dry-run", action="store_true", help="Validate only, don't render")
    parser.add_argument("--report", default="-", help="JSON report output path or - for stdout")
    args = parser.parse_args()

    report = finalize(
        Path(args.base_dir),
        Path(args.output_path),
        transition=args.transition,
        transition_duration=args.transition_duration,
        auto_normalize=args.auto_normalize,
        codec=args.codec,
        crf=args.crf,
        preset=args.preset,
        dry_run=args.dry_run,
    )

    payload = json.dumps(report, ensure_ascii=False, indent=2)
    if args.report == "-":
        print(payload)
    else:
        Path(args.report).write_text(payload, encoding="utf-8")


if __name__ == "__main__":
    main()